export { default as firstCandyCard } from './firstCard'
export { default as secondCandyCard } from './secondCard'
export { default as thirdCandyCard } from './thirdCard'
export { default as fourthCandyCard } from './fourthCard'
export { default as fifthCandyCard } from './fifthCard'
export { default as sixthCandyCard } from './sixthCard'